name: container

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create additional environment variables
        run: |
          # get the tag and remove prefix
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//refs\/tags\//})
          echo "::set-env name=RELEASE_VERSION::${RELEASE_VERSION//v/}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish container
        uses: docker/build-push-action@v2
        with:
          build_args: RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REPOSITORY }}:${{ env.RELEASE_VERSION }}
